name: 🚀 Release

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install tools
        run: pip install python-semantic-release commitizen
      - name: Publish release
        run: semantic-release publish
